- name: Creations des utilisateurs
  mysql_user:
    name: "{{ item }}"
    password: "{{ item }}"
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    priv: '*.*:ALL,GRANT'
    state: present
  loop: "{{ bdd }}"    
  become: true

- name: Creation des bases de donnees joomla et vaultwarden
  community.mysql.mysql_db:
    name: "{{ item }}"
    state: present
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
  loop: "{{ bdd }}" 
  become: true 
