- name: Mise à jour du cache APT
  ansible.builtin.apt:
    state: absent
    update_cache: true
  become: true

- name: Installation tmux et emacs en mm tps (loop)  
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ prog }}"
  become: true
