- name: create user
  ansible.builtin.user:
    name: "{{ item.name }}"
    #uid: "{{ uid }}"
    password: "{{ item.password }}"
    append: true
    groups: "{{ item.groups }}"
    shell: "{{ shell }}"
    system: false
    createhome: true
    home: "/home/{{ item.name }}"
    comment: "{{ comment }} {{ item.name }}"
  loop: "{{ userclient }}"
  state: present
  become: true
