uid: 20001
shell: "/bin/bash"
userclient:
  - { name: "joomla", groups: "joomla", password: "joomla"} 
  - { name: "vaultwarden", groups: "vaultwarden", password: "vaultwarden"} 
comment: "Creation du user "
